### ISSUE TITLE
Link under description 404s

### ISSUE THREAD

**Issue by o-az** [skip-mev/block-sdk#464]
![CleanShot 2024-03-28 at 11 26 23](https://github.com/skip-mev/block-sdk/assets/23618431/f1371825-3427-4d21-aea0-f251dc99fb4d)

[docs.skip.money/chains/overview](https://docs.skip.money/chains/overview)

I would update it myself but can't change that field through a pr. Should it be [this](https://docs.skip.money/blocksdk/overview)?

**Comment by Zygimantass** [comment]
thanks for the heads up, done
