### ISSUE TITLE
Fix Escrow Address RPC

### ISSUE THREAD

**Issue by davidterpay** [skip-mev/block-sdk#99]
When fetching the escrow address from the `x/auction` module, the response includes the bytes of the address when it should return the bech32 address. Simple fix here is to return a string type and convert the bytes to the corrected address.

**Comment by 0xRampey** [comment]
Hey is this open to public contributors?

**Comment by davidterpay** [comment]
hey @0xRampey! yes, this repo is open for public contributors. feel free to fork the repo and make contributions!

**Comment by davidterpay** [comment]
This has been fixed and is in the alpha pre-releases.
